services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/templates/:/etc/nginx/templates/
      - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh  # Script to autoreload Nginx when certs are renewed
    networks:
      - nginx_net
    restart: unless-stopped
    env_file: .env

  certbot:
    image: certbot/certbot 
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  # Renew certificates every 12 hours
    networks:
      - nginx_net
    restart: unless-stopped

volumes:
  shared_confs:
    name: shared_confs

networks:
  nginx_net:
    name: nginx_net
    driver: bridge

