services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_confs:/etc/nginx/conf.d  # Configs centralizadas
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - nginx_net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - nginx_net
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  shared_confs:    # Volumen para todas las configs
    name: shared_confs # Fuerza este nombre exacto
  certbot_www:
  certbot_conf:

networks:
  nginx_net:      # Red compartida para todos los proyectos
    name: nginx_net  # Fuerza este nombre exacto

