services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./shared_confs:/etc/nginx/conf.d
      - ./nginx/secure/:/etc/nginx/templates/
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh  # Script to autoreload Nginx when certs are renewed
    networks:
      - nginx_net
    restart: unless-stopped
    env_file: .env

  certbot:
    image: certbot/certbot
    networks:
      - nginx_net
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  # Renew certificates every 12 hours
    restart: unless-stopped

volumes:
  shared_confs:
    name: shared_confs  # Nombre fijo para compartir

networks:
  nginx_net:
    name: nginx_net  # Nombre fijo para la red
    driver: bridge

