services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_confs:/etc/nginx/conf.d
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - nginx_net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - nginx_net
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  shared_confs:
    name: shared_confs  # Nombre fijo para compartir
  certbot_www:
  certbot_conf:

networks:
  nginx_net:
    name: nginx_net  # Nombre fijo para la red
    driver: bridge   # Importante definirlo aquí primero
